---
- name: update systems
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
  - apt:
      name: "*"
      state: latest
      force_apt_get: true
      update_cache: true
      autoremove: true